# Introdução à Linguagem Julia

Julia é uma linguagem dinâmica de alto nível e alto desempenho.
Ela se assemelha ao MatLab e ao Python na facilidade de escrita
de código, mas sua velocidade pode ser comparável ao C e Fortran.

# Jupyter

O Jupyter é uma interface web para Julia, Python, e muitas outras.
Ela **não** é o Julia, isto é, o Julia não depende do Jupyter para
funcionar. No entanto, usando o Jupyter, aulas e apresentações
ficam mais práticas.

Cada *célula* do Jupyter pode ser executada com um `ctrl+enter`, ou
um `ctrl+shift`, sendo que o último move a seleção para a célula de
baixo.
Você pode adicionar novas células usando o `+` no topo da página.

# O REPL - Terminal Interativo

Ao abrir o Julia no Windows, ou digitar `julia` no terminal do Mac
ou Linux, se abrirá um prompt tipo

````julia
julia>
````

O Jupyter também serve como esse prompt e todo comando digitado aqui
pode ser digitado lá.

# Básico

In [1]:
2 + 3

5

In [2]:
3 * 5

15

In [3]:
7 ^ 3

343

In [4]:
exp(2)

7.38905609893065

In [5]:
sin(3.14159/4)

0.7071063120935576

In [6]:
pi

π = 3.1415926535897...

In [7]:
sin(pi/4)

0.7071067811865475

In [8]:
round(1.2)

1.0

In [123]:
sqrt(2)

1.4142135623730951

In [9]:
abs(-3)

3

In [10]:
x = 3

3

In [11]:
x ^ 2

9

In [12]:
y = 2x

6

In [13]:
y - x

3

In [14]:
1e-2 # 10⁻²

0.01

In [15]:
1e3 # 10³

1000.0

In [16]:
0.1 + 0.2 - 0.3

5.551115123125783e-17

## Exercício

- Calcule $\varphi = \dfrac{\sqrt{5} + 1}{2}$.

# Álgebra Linear Numérica

In [17]:
rand(3)

3-element Array{Float64,1}:
 0.285575
 0.673474
 0.925352

In [18]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [19]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [20]:
rand(2,4)

2×4 Array{Float64,2}:
 0.736333  0.437507  0.873963  0.982646
 0.819335  0.252318  0.286225  0.314942

In [21]:
v = rand(3)

3-element Array{Float64,1}:
 0.973007
 0.465695
 0.352008

In [22]:
A = rand(2, 3)

2×3 Array{Float64,2}:
 0.460065  0.806683  0.636721
 0.706877  0.811051  0.91831 

In [23]:
A * v

2-element Array{Float64,1}:
 1.04745
 1.38875

In [24]:
w = rand(2)

2-element Array{Float64,1}:
 0.18481 
 0.862083

In [25]:
A' * w

3-element Array{Float64,1}:
 0.694411
 0.848277
 0.909332

In [26]:
B = rand(2, 3)

2×3 Array{Float64,2}:
 0.456517  0.13849   0.037809
 0.463185  0.467513  0.182055

In [27]:
A + B

2×3 Array{Float64,2}:
 0.916582  0.945173  0.67453
 1.17006   1.27856   1.10037

In [28]:
A * B'

2×2 Array{Float64,2}:
 0.345819  0.706148
 0.469745  0.873775

In [29]:
A' * B

3×3 Array{Float64,2}:
 0.537442  0.394189  0.146085
 0.743931  0.490895  0.178156
 0.716021  0.517502  0.191257

In [30]:
A = rand(3, 3)
b = rand(3)
x = A\b # Resolve o SL

3-element Array{Float64,1}:
  1.42637
  1.71667
 -1.73424

In [31]:
A * x - b # É pra ser zero (ou quase)

3-element Array{Float64,1}:
 -1.11022e-16
 -2.22045e-16
  0.0        

In [32]:
norm(A*x-b) # norm = ‖ ⋅ ‖

2.482534153247273e-16

In [33]:
v = [1.0; 2.0; 3.0]
w = [2.0; -2.0; 2.0]
dot(v, w) # ⟨v,w⟩

4.0

In [34]:
det(A)

0.09412184591788629

In [35]:
A^2 # A * A

3×3 Array{Float64,2}:
 0.83915   0.517376  0.841767
 1.18437   0.817453  1.23575 
 0.873454  1.07266   1.28919 

In [36]:
A .^ 2 # Cada elemento de A ao quadrado

3×3 Array{Float64,2}:
 0.720778    0.00999643  0.211325
 0.822554    0.17099     0.426659
 0.00362927  0.723989    0.70571 

In [37]:
B = rand(3, 3)

3×3 Array{Float64,2}:
 0.42288    0.17571   0.324742
 0.0538742  0.95668   0.111605
 0.863157   0.480469  0.563399

In [38]:
A .* B

3×3 Array{Float64,2}:
 0.35902    0.0175679  0.149284 
 0.0488611  0.395597   0.0728991
 0.0519996  0.408819   0.473292 

## Funções que "distribuem"

In [124]:
exp([0.0; 1.0])

2-element Array{Float64,1}:
 1.0    
 2.71828

In [126]:
sqrt(linspace(0, 1, 10))

10-element Array{Float64,1}:
 0.0     
 0.333333
 0.471405
 0.57735 
 0.666667
 0.745356
 0.816497
 0.881917
 0.942809
 1.0     

## Exercício

- Crie um vetor com os ângulos importantes: 0, pi/6, pi/4, pi/3 e pi/2.
- Crie um vetor com o seno de cada ângulo e outro com o cosseno, usando o vetor acima.
- Calcule a tangente de cada angulo usando os dois vetores acima (tan = sen/cos), mas **sem usar a função tan**.

## Acesso aos elementos

In [39]:
v

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [40]:
v[1]

1.0

In [41]:
v[2]

2.0

In [42]:
A

3×3 Array{Float64,2}:
 0.848986   0.0999822  0.459701
 0.906948   0.41351    0.653191
 0.0602434  0.850875   0.840066

In [43]:
A[1,1]

0.8489864011931925

In [44]:
A[2,3]

0.653191022758979

In [45]:
v[1:2]

2-element Array{Float64,1}:
 1.0
 2.0

In [46]:
A[:,2]

3-element Array{Float64,1}:
 0.0999822
 0.41351  
 0.850875 

In [47]:
A[1,:]

3-element Array{Float64,1}:
 0.848986 
 0.0999822
 0.459701 

In [48]:
A[2,3] = 0.0

0.0

In [49]:
A

3×3 Array{Float64,2}:
 0.848986   0.0999822  0.459701
 0.906948   0.41351    0.0     
 0.0602434  0.850875   0.840066

In [50]:
eye(3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [51]:
m, n = size(A)

(3,3)

In [52]:
length(v)

3

## Exercício

- Crie um vetor aleatório e mude o primeiro elemento para o seu oposto (i.e. mude o sinal)

## Matriz por blocos - concatenação

In [53]:
[rand(3,3) zeros(3,2); ones(2,3) eye(2,2)]

5×5 Array{Float64,2}:
 0.828059  0.161645  0.307942  0.0  0.0
 0.863721  0.425897  0.350354  0.0  0.0
 0.6384    0.989955  0.419942  0.0  0.0
 1.0       1.0       1.0       1.0  0.0
 1.0       1.0       1.0       0.0  1.0

# Funções

In [54]:
f(x) = x^2
f(2)

4

In [55]:
f(-3)

9

In [56]:
g(a,b) = exp(a + b)

g (generic function with 1 method)

In [57]:
g(2,3)

148.4131591025766

In [58]:
g(3,-3)

1.0

In [59]:
h = x -> sin(x)

(::#1) (generic function with 1 method)

In [60]:
h(2)

0.9092974268256817

In [61]:
function aprox_der(f, a, h)
    (f(a+h) - f(a))/h
end

aprox_der (generic function with 1 method)

In [62]:
aprox_der(h, pi/6, 1e-8)

0.8660254013914681

In [63]:
function aprox_der(f, a, h = 1e-8)
    (f(a+h) - f(a))/h
end

aprox_der (generic function with 2 methods)

In [64]:
aprox_der(h, pi/6)

0.8660254013914681

In [65]:
aprox_der(x->x^2+3x+2, 2) # 2x + 3 com x = 2: 7

6.999999868639861

## Vetor vs Array vs Array 1xN vs Array Nx1

In [66]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [67]:
[1.0 1.0 1.0]

1×3 Array{Float64,2}:
 1.0  1.0  1.0

In [68]:
[1.0; 1.0; 1.0]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [69]:
[1.0, 1.0, 1.0]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [70]:
[1.0 1.0 1.0]'

3×1 Array{Float64,2}:
 1.0
 1.0
 1.0

# Exercícios

- Crie uma função que recebe $a$ e calcula $2\bigg(a + \dfrac{1}{a}\bigg)$.
- Crie uma função que recebe dois catetos e calcula a hipotenusa.
- Crie uma função que recebe uma matriz A e um vetor v e retorna
$\dfrac{\langle v, Av\rangle}{\langle v, v\rangle}$

# Loops e condicionais

In [127]:
for i = 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [128]:
for i = 1:10
    print(i)
end

12345678910

In [129]:
for i = 1:10
    println("i = $i")
end

i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
i = 9
i = 10


In [130]:
x = rand(10)
y = zeros(10)
for i = 1:10
    y[i] = x[i] * i
end

In [131]:
x

10-element Array{Float64,1}:
 0.796215 
 0.146132 
 0.453449 
 0.514267 
 0.925038 
 0.213549 
 0.548834 
 0.0764831
 0.340822 
 0.778201 

In [132]:
y

10-element Array{Float64,1}:
 0.796215
 0.292264
 1.36035 
 2.05707 
 4.62519 
 1.28129 
 3.84183 
 0.611865
 3.0674  
 7.78201 

In [133]:
for x in [0; pi/6; pi/4; pi/3; pi/2]
    println("sin($x) = $(sin(x))")
end

sin(0.0) = 0.0
sin(0.5235987755982988) = 0.49999999999999994
sin(0.7853981633974483) = 0.7071067811865475
sin(1.0471975511965976) = 0.8660254037844386
sin(1.5707963267948966) = 1.0


In [134]:
for i = 3:3:20
    print("$i ")
end

3 6 9 12 15 18 

In [79]:
for x in Any["a", 0, 3.14, e, 3//4, im, ones(2), ones(2,2)]
    println("x: $x    Tipo: $(typeof(x))")
end

x: a    Tipo: String
x: 0    Tipo: Int64
x: 3.14    Tipo: Float64
x: e = 2.7182818284590...    Tipo: Irrational{:e}
x: 3//4    Tipo: Rational{Int64}
x: im    Tipo: Complex{Bool}
x: [1.0,1.0]    Tipo: Array{Float64,1}
x: [1.0 1.0; 1.0 1.0]    Tipo: Array{Float64,2}


In [80]:
n = 6
v = ones(n)
v[n/2] = 2
v

LoadError: LoadError: ArgumentError: invalid index: 3.0
while loading In[80], in expression starting on line 3

In [81]:
n/2

3.0

In [82]:
div(n,2)

3

In [83]:
round(Int, n/2)

3

In [84]:
10 % 4

2

# Fatorial
$$ n! = n(n-1)\dots2. 1 $$

In [85]:
function fatorial(n)
    resultado = 1
    for i = 1:n
        resultado = resultado * i
    end
    return resultado
end

fatorial (generic function with 1 method)

In [86]:
fatorial(4)

24

In [87]:
fatorial(5)

120

In [88]:
fatorial(0)

1

## Exercícios

- Faça uma função `soma1(n)` que calcula a soma $1 + 2 + 3 + \dots + n$, usando `for`. (O valor exato é `n(n+1)/2`).
- Faça uma função `soma2(n)` que calcula a soma $1^2 + 2^2 + \dots + n^2$, usando `for`. (O valor exato é `n(n+1)(2n+1)/6`).

In [89]:
function sinal(x)
    if x > 0
        return 1
    elseif x < 0
        return -1
    else
        return 0
    end
end

sinal (generic function with 1 method)

In [90]:
sinal(3.2)

1

In [91]:
sinal(-1.2)

-1

In [92]:
sinal(0.0)

0

In [93]:
function bhaskara(a, b, c)
    Δ = b^2 - 4a*c
    if Δ < 0
        error("Nos reais não tem solução")
    end
    return (-b + sqrt(Δ))/2a, (-b - sqrt(Δ))/2a
end

bhaskara (generic function with 1 method)

In [94]:
bhaskara(1, 5, 6)

(-2.0,-3.0)

In [95]:
bhaskara(1, 0, 1)

LoadError: LoadError: Nos reais não tem solução
while loading In[95], in expression starting on line 1

In [96]:
bhaskara(1, 0, -1)

(1.0,-1.0)

## Exercícios

- Faça uma função `primo(n)` que retorna se o número `n` é primo ou não. Lembrando que `n % p` é o resto da divisão de `n` por `p`.

In [97]:
function ordem(N) # ordem(12) = 1, ordem(500) = 2
    n = 0
    while N > 10
        n = n + 1
        N = N/10
    end
    return n
end

ordem (generic function with 1 method)

In [98]:
ordem(12)

1

In [99]:
ordem(500)

2

In [100]:
ordem(-1) # Não funciona

0

## Exercícios

- Faça uma função `collatz(n)` que calcula uma sequência
$$ a_{n+1} = \left\{\begin{array}{ll}
a_n/2, & \mbox{se $a_n$ é par} \\
3a_n + 1, & \mbox{se $a_n$ é ímpar}.
\end{array}\right.$$
começando de $a_0 = n$, e parando quando $a_n = 1$.
Imprima cada elemento da sequência.

## Operadores lógicos

In [166]:
true

true

In [167]:
true || false

true

In [168]:
true && false

false

In [169]:
if 1 > 0 && "a" in ["a", "b"]
    println("Ok")
end

Ok


In [171]:
function fib(n)
    if (n == 1 || n == 2)
        return 1
    else
        return fib(n-1) + fib(n-2)
    end
end

fib (generic function with 1 method)

In [172]:
fib(1)

1

In [173]:
fib(2)

1

In [175]:
fib(3)

2

In [176]:
fib(5)

5

In [178]:
!true

false

## !(a && b) = !a || !b

In [216]:
x = 0
n = 0

while !(x > 5 || n == 10)
    x = x + rand()
    n = n + 1
end
println("Fim, x = $x, n = $n")

Fim, x = 5.916196541010944, n = 8


In [221]:
n = 0
x = 0

while x <= 5 && n < 10
    x = x + rand()
    n = n + 1
end
println("Fim, x = $x, n = $n")

Fim, x = 5.0185272613344, n = 9


In [222]:
## Curto circuito
function imprime_se_positivo(x)
    x > 0 && println("x positivo")
end

imprime_se_positivo (generic function with 1 method)

In [223]:
imprime_se_positivo(1)

x positivo


In [224]:
imprime_se_positivo(0)

false

In [225]:
## Operador ternário
1 > 0 ? "ok" : "nao"

"ok"

In [226]:
maximo(a, b) = a > b ? a : b

maximo (generic function with 1 method)

In [230]:
maximo(2, 3)

3

In [231]:
maximo(5, 3)

5

## Arquivos

In [135]:
;cat exemplo.jl

# Este é um arquivo de exemplo

"""
    y = aprox_log(x)

Retorna um valor aproximado para `log(x)`, utilizando
a expansão

$$ \ln(x) = 2\bigg(\frac{x-1}{x+1} + \frac{1}{3}\bigg(\frac{x-1}{x+1}\bigg)^3
+ \frac{1}{5}\bigg(\frac{x-1}{x+1}\bigg)^5 + \dots\bigg)
"""
function aprox_log(x)
    y = (x-1)/(x+1)
    return 2*(y + y^3/3 + y^5/5)
end

In [136]:
aprox_log(2)

LoadError: LoadError: UndefVarError: aprox_log not defined
while loading In[136], in expression starting on line 1

In [162]:
include("exemplo.jl")

aprox_log

In [163]:
aprox_log(2)

0.6930041152263374

In [164]:
?aprox_log

search:



```
y = aprox_log(x)
```

Retorna um valor aproximado para `log(x)`, utilizando a expansão

ln(x) = 2(z + z^3/3 + z^5/5 + ...)

onde z = (x-1)/(x+1).


In [165]:
log(2)

0.6931471805599453

## Pacotes

http://pkg.julialang.org/ ou busque no google.

### Instalação de pacotes

In [105]:
# Não rode pois leva um tempo
error("Não rode")
Pkg.add("Plots")
Pkg.clone("https://github.com/abelsiqueira/NLPModels.jl")
Pkg.build("NLPModels.jl")

LoadError: LoadError: Não rode
while loading In[105], in expression starting on line 2

Fazer um pacote dá bastante mais trabalho. Ele exige uma hierarquia
específica do diretório. Só a criação decente de um pacote já seria
uma aula.

Veja http://abelsiqueira.github.io/blog/test-driven-development-in-julia/
e http://abelsiqueira.github.io/blog/automated-testing/
para mais informações, ou o próprio help.

## Plots

In [106]:
using Plots
gr()

Plots.GRBackend()

In [107]:
plot([1; 2; 3], [3; 1; 2])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 
 
 
 
 y1

In [108]:
x = linspace(0, 1, 100)
y = x.^2
plot(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 30.6037,384.952 36.3154,384.913 42.0271,384.796 47.7388,384.602 53.4505,384.33 59.1622,383.98 64.8739,383.552 70.5856,383.047 76.2974,382.464 82.0091,381.803 
 87.7208,381.064 93.4325,380.248 99.1442,379.354 104.856,378.382 110.568,377.332 116.279,376.205 121.991,375 127.703,373.717 133.414,372.356 139.126,370.918 
 144.838,369.402 150.55,367.808 156.261,366.136 161.973,364.387 167.685,362.56 173.396,360.655 179.108,358.672 184.82,356.612 190.532,354.474 196.243,352.258 
 201.955,349.964 207.667,347.593 213.378,345.144 219.09,342.617 224.802,340.012 230.514,337.33 236.225,334.57 241.937,331.732 247.649,328.816 253.36,325.823 
 259.072,322.752 264.784,319.603 270.496,316.376 276.207,313.072 281.919,309.69 287.631,306.23 293.342,302.692 299.054,299.077 304.766,295.384 310.477,291.613 
 316.189,287.764 321.901,283.838 327.613,279.834 333.324,275.752 339.036,271.592 344.748,267.355 350.459,263.04 356.171,258.647 361.883,254.176 367.595,249.628 
 373.306,245.002 379.018,240.298 384.73,235.516 390.441,230.657 396.153,225.719 401.865,220.705 407.577,215.612 413.288,210.442 419,205.193 424.712,199.868 
 430.423,194.464 436.135,188.982 441.847,183.423 447.559,177.786 453.27,172.072 458.982,166.279 464.694,160.409 470.405,154.461 476.117,148.436 481.829,142.332 
 487.54,136.151 493.252,129.892 498.964,123.556 504.676,117.141 510.387,110.649 516.099,104.079 521.811,97.4316 527.522,90.7062 533.234,83.9031 538.946,77.0222 
 544.658,70.0636 550.369,63.0272 556.081,55.913 561.793,48.7211 567.504,41.4515 573.216,34.1041 578.928,26.6789 584.64,19.176 590.351,11.5954 596.063,3.93701 
 
 "/>
 
 
 
 
 y1

In [109]:
scatter(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [110]:
scatter(x, rand(100))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [111]:
f(x) = sin(x)
plot(f, 0, 4pi)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 5 
 
 
 10 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 39.4926,194.444 45.1145,170.325 50.7364,146.593 56.3583,123.631 61.9803,101.809 67.6022,81.4769 73.2241,62.9627 78.846,46.5642 84.468,32.5451 90.0899,21.131 
 95.7118,12.5056 101.334,6.80763 106.956,4.12883 112.578,4.51229 118.199,7.95183 123.821,14.3921 129.443,23.7295 135.065,35.8137 140.687,50.4504 146.309,67.404 
 151.931,86.4017 157.553,107.138 163.175,129.279 168.797,152.468 174.419,176.333 180.041,200.49 185.663,224.549 191.284,248.123 196.906,270.834 202.528,292.316 
 208.15,312.223 213.772,330.235 219.394,346.062 225.016,359.449 230.638,370.182 236.26,378.087 241.882,383.037 247.504,384.952 253.126,383.802 258.748,379.605 
 264.37,372.429 269.991,362.389 275.613,349.647 281.235,334.407 286.857,316.916 292.479,297.454 298.101,276.334 303.723,253.897 309.345,230.503 314.967,206.529 
 320.589,182.36 326.211,158.386 331.833,134.992 337.455,112.555 343.076,91.4354 348.698,71.9732 354.32,54.4816 359.942,39.2421 365.564,26.4999 371.186,16.4599 
 376.808,9.28381 382.43,5.08699 388.052,3.93701 393.674,5.85236 399.296,10.8022 404.918,18.707 410.54,29.4394 416.161,42.8268 421.783,58.6538 427.405,76.6657 
 433.027,96.5728 438.649,118.055 444.271,140.766 449.893,164.34 455.515,188.399 461.137,212.556 466.759,236.421 472.381,259.61 478.003,281.751 483.625,302.487 
 489.246,321.485 494.868,338.438 500.49,353.075 506.112,365.159 511.734,374.497 517.356,380.937 522.978,384.377 528.6,384.76 534.222,382.081 539.844,376.383 
 545.466,367.758 551.088,356.344 556.71,342.325 562.331,325.926 567.953,307.412 573.575,287.08 579.197,265.258 584.819,242.296 590.441,218.564 596.063,194.444 
 
 "/>
 
 
 
 
 y1

In [112]:
plot(x->exp(x), -1, 1)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,384.952 18.7172,383.735 24.6085,382.493 30.4997,381.226 36.391,379.933 42.2823,378.613 48.1736,377.267 54.0649,375.893 59.9562,374.491 65.8475,373.061 
 71.7387,371.601 77.63,370.112 83.5213,368.592 89.4126,367.041 95.3039,365.458 101.195,363.844 107.086,362.196 112.978,360.514 118.869,358.799 124.76,357.048 
 130.652,355.261 136.543,353.439 142.434,351.578 148.325,349.68 154.217,347.744 160.108,345.767 165.999,343.751 171.891,341.693 177.782,339.593 183.673,337.45 
 189.564,335.264 195.456,333.033 201.347,330.756 207.238,328.433 213.13,326.063 219.021,323.644 224.912,321.176 230.803,318.657 236.695,316.087 242.586,313.465 
 248.477,310.789 254.369,308.059 260.26,305.273 266.151,302.429 272.042,299.528 277.934,296.568 283.825,293.547 289.716,290.465 295.608,287.32 301.499,284.11 
 307.39,280.835 313.281,277.494 319.173,274.084 325.064,270.604 330.955,267.054 336.847,263.431 342.738,259.734 348.629,255.961 354.52,252.112 360.412,248.184 
 366.303,244.176 372.194,240.086 378.085,235.913 383.977,231.654 389.868,227.309 395.759,222.875 401.651,218.35 407.542,213.733 413.433,209.022 419.324,204.215 
 425.216,199.309 431.107,194.304 436.998,189.196 442.89,183.984 448.781,178.666 454.672,173.239 460.563,167.702 466.455,162.051 472.346,156.285 478.237,150.402 
 484.129,144.398 490.02,138.272 495.911,132.021 501.802,125.642 507.694,119.133 513.585,112.492 519.476,105.714 525.368,98.7988 531.259,91.7422 537.15,84.5415 
 543.041,77.1939 548.933,69.6963 554.824,62.0457 560.715,54.239 566.607,46.273 572.498,38.1444 578.389,29.8499 584.28,21.3862 590.172,12.7497 596.063,3.93701 
 
 "/>
 
 
 
 
 y1

In [113]:
plot!(x->exp(-x), -1, 1)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,384.952 18.7172,383.735 24.6085,382.493 30.4997,381.226 36.391,379.933 42.2823,378.613 48.1736,377.267 54.0649,375.893 59.9562,374.491 65.8475,373.061 
 71.7387,371.601 77.63,370.112 83.5213,368.592 89.4126,367.041 95.3039,365.458 101.195,363.844 107.086,362.196 112.978,360.514 118.869,358.799 124.76,357.048 
 130.652,355.261 136.543,353.439 142.434,351.578 148.325,349.68 154.217,347.744 160.108,345.767 165.999,343.751 171.891,341.693 177.782,339.593 183.673,337.45 
 189.564,335.264 195.456,333.033 201.347,330.756 207.238,328.433 213.13,326.063 219.021,323.644 224.912,321.176 230.803,318.657 236.695,316.087 242.586,313.465 
 248.477,310.789 254.369,308.059 260.26,305.273 266.151,302.429 272.042,299.528 277.934,296.568 283.825,293.547 289.716,290.465 295.608,287.32 301.499,284.11 
 307.39,280.835 313.281,277.494 319.173,274.084 325.064,270.604 330.955,267.054 336.847,263.431 342.738,259.734 348.629,255.961 354.52,252.112 360.412,248.184 
 366.303,244.176 372.194,240.086 378.085,235.913 383.977,231.654 389.868,227.309 395.759,222.875 401.651,218.35 407.542,213.733 413.433,209.022 419.324,204.215 
 425.216,199.309 431.107,194.304 436.998,189.196 442.89,183.984 448.781,178.666 454.672,173.239 460.563,167.702 466.455,162.051 472.346,156.285 478.237,150.402 
 484.129,144.398 490.02,138.272 495.911,132.021 501.802,125.642 507.694,119.133 513.585,112.492 519.476,105.714 525.368,98.7988 531.259,91.7422 537.15,84.5415 
 543.041,77.1939 548.933,69.6963 554.824,62.0457 560.715,54.239 566.607,46.273 572.498,38.1444 578.389,29.8499 584.28,21.3862 590.172,12.7497 596.063,3.93701 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,3.93701 18.7172,12.7497 24.6085,21.3862 30.4997,29.8499 36.391,38.1444 42.2823,46.273 48.1736,54.239 54.0649,62.0457 59.9562,69.6963 65.8475,77.1939 
 71.7387,84.5415 77.63,91.7422 83.5213,98.7988 89.4126,105.714 95.3039,112.492 101.195,119.133 107.086,125.642 112.978,132.021 118.869,138.272 124.76,144.398 
 130.652,150.402 136.543,156.285 142.434,162.051 148.325,167.702 154.217,173.239 160.108,178.666 165.999,183.984 171.891,189.196 177.782,194.304 183.673,199.309 
 189.564,204.215 195.456,209.022 201.347,213.733 207.238,218.35 213.13,222.875 219.021,227.309 224.912,231.654 230.803,235.913 236.695,240.086 242.586,244.176 
 248.477,248.184 254.369,252.112 260.26,255.961 266.151,259.734 272.042,263.431 277.934,267.054 283.825,270.604 289.716,274.084 295.608,277.494 301.499,280.835 
 307.39,284.11 313.281,287.32 319.173,290.465 325.064,293.547 330.955,296.568 336.847,299.528 342.738,302.429 348.629,305.273 354.52,308.059 360.412,310.789 
 366.303,313.465 372.194,316.087 378.085,318.657 383.977,321.176 389.868,323.644 395.759,326.063 401.651,328.433 407.542,330.756 413.433,333.033 419.324,335.264 
 425.216,337.45 431.107,339.593 436.998,341.693 442.89,343.751 448.781,345.767 454.672,347.744 460.563,349.68 466.455,351.578 472.346,353.439 478.237,355.261 
 484.129,357.048 490.02,358.799 495.911,360.514 501.802,362.196 507.694,363.844 513.585,365.458 519.476,367.041 525.368,368.592 531.259,370.112 537.15,371.601 
 543.041,373.061 548.933,374.491 554.824,375.893 560.715,377.267 566.607,378.613 572.498,379.933 578.389,381.226 584.28,382.493 590.172,383.735 596.063,384.952 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [114]:
xlims!(-0.5, 0.5)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -0.50 
 
 
 -0.25 
 
 
 0.00 
 
 
 0.25 
 
 
 0.50 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -278.793,384.952 -267.01,383.735 -255.228,382.493 -243.445,381.226 -231.662,379.933 -219.88,378.613 -208.097,377.267 -196.315,375.893 -184.532,374.491 -172.75,373.061 
 -160.967,371.601 -149.184,370.112 -137.402,368.592 -125.619,367.041 -113.837,365.458 -102.054,363.844 -90.2716,362.196 -78.489,360.514 -66.7064,358.799 -54.9239,357.048 
 -43.1413,355.261 -31.3587,353.439 -19.5762,351.578 -7.7936,349.68 3.98897,347.744 15.7715,345.767 27.5541,343.751 39.3367,341.693 51.1192,339.593 62.9018,337.45 
 74.6844,335.264 86.4669,333.033 98.2495,330.756 110.032,328.433 121.815,326.063 133.597,323.644 145.38,321.176 157.162,318.657 168.945,316.087 180.727,313.465 
 192.51,310.789 204.293,308.059 216.075,305.273 227.858,302.429 239.64,299.528 251.423,296.568 263.205,293.547 274.988,290.465 286.771,287.32 298.553,284.11 
 310.336,280.835 322.118,277.494 333.901,274.084 345.683,270.604 357.466,267.054 369.249,263.431 381.031,259.734 392.814,255.961 404.596,252.112 416.379,248.184 
 428.161,244.176 439.944,240.086 451.727,235.913 463.509,231.654 475.292,227.309 487.074,222.875 498.857,218.35 510.639,213.733 522.422,209.022 534.205,204.215 
 545.987,199.309 557.77,194.304 569.552,189.196 581.335,183.984 593.117,178.666 604.9,173.239 616.682,167.702 628.465,162.051 640.248,156.285 652.03,150.402 
 663.813,144.398 675.595,138.272 687.378,132.021 699.16,125.642 710.943,119.133 722.726,112.492 734.508,105.714 746.291,98.7988 758.073,91.7422 769.856,84.5415 
 781.638,77.1939 793.421,69.6963 805.204,62.0457 816.986,54.239 828.769,46.273 840.551,38.1444 852.334,29.8499 864.116,21.3862 875.899,12.7497 887.682,3.93701 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -278.793,3.93701 -267.01,12.7497 -255.228,21.3862 -243.445,29.8499 -231.662,38.1444 -219.88,46.273 -208.097,54.239 -196.315,62.0457 -184.532,69.6963 -172.75,77.1939 
 -160.967,84.5415 -149.184,91.7422 -137.402,98.7988 -125.619,105.714 -113.837,112.492 -102.054,119.133 -90.2716,125.642 -78.489,132.021 -66.7064,138.272 -54.9239,144.398 
 -43.1413,150.402 -31.3587,156.285 -19.5762,162.051 -7.7936,167.702 3.98897,173.239 15.7715,178.666 27.5541,183.984 39.3367,189.196 51.1192,194.304 62.9018,199.309 
 74.6844,204.215 86.4669,209.022 98.2495,213.733 110.032,218.35 121.815,222.875 133.597,227.309 145.38,231.654 157.162,235.913 168.945,240.086 180.727,244.176 
 192.51,248.184 204.293,252.112 216.075,255.961 227.858,259.734 239.64,263.431 251.423,267.054 263.205,270.604 274.988,274.084 286.771,277.494 298.553,280.835 
 310.336,284.11 322.118,287.32 333.901,290.465 345.683,293.547 357.466,296.568 369.249,299.528 381.031,302.429 392.814,305.273 404.596,308.059 416.379,310.789 
 428.161,313.465 439.944,316.087 451.727,318.657 463.509,321.176 475.292,323.644 487.074,326.063 498.857,328.433 510.639,330.756 522.422,333.033 534.205,335.264 
 545.987,337.45 557.77,339.593 569.552,341.693 581.335,343.751 593.117,345.767 604.9,347.744 616.682,349.68 628.465,351.578 640.248,353.439 652.03,355.261 
 663.813,357.048 675.595,358.799 687.378,360.514 699.16,362.196 710.943,363.844 722.726,365.458 734.508,367.041 746.291,368.592 758.073,370.112 769.856,371.601 
 781.638,373.061 793.421,374.491 805.204,375.893 816.986,377.267 828.769,378.613 840.551,379.933 852.334,381.226 864.116,382.493 875.899,383.735 887.682,384.952 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [115]:
ylims!(0.5, 1.5)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -0.50 
 
 
 -0.25 
 
 
 0.00 
 
 
 0.25 
 
 
 0.50 
 
 
 0.50 
 
 
 0.75 
 
 
 1.00 
 
 
 1.25 
 
 
 1.50 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -238.793,435.292 -227.549,432.431 -216.305,429.512 -205.061,426.534 -193.817,423.495 -182.573,420.394 -171.33,417.229 -160.086,414 -148.842,410.705 -137.598,407.343 
 -126.354,403.912 -115.11,400.411 -103.866,396.839 -92.6226,393.194 -81.3788,389.474 -70.1349,385.679 -58.8911,381.806 -47.6473,377.854 -36.4034,373.821 -25.1596,369.706 
 -13.9157,365.507 -2.67186,361.223 8.57198,356.851 19.8158,352.389 31.0597,347.837 42.3035,343.192 53.5474,338.452 64.7912,333.615 76.0351,328.68 87.2789,323.644 
 98.5228,318.505 109.767,313.261 121.01,307.91 132.254,302.45 143.498,296.879 154.742,291.194 165.986,285.393 177.23,279.473 188.474,273.433 199.717,267.269 
 210.961,260.98 222.205,254.562 233.449,248.013 244.693,241.331 255.937,234.512 267.18,227.554 278.424,220.455 289.668,213.21 300.912,205.817 312.156,198.274 
 323.4,190.576 334.644,182.722 345.887,174.707 357.131,166.529 368.375,158.183 379.619,149.668 390.863,140.979 402.107,132.112 413.35,123.064 424.594,113.832 
 435.838,104.411 447.082,94.7986 458.326,84.9895 469.57,74.9803 480.814,64.7668 492.057,54.3449 503.301,43.7102 514.545,32.8586 525.789,21.7855 537.033,10.4864 
 548.277,-1.04327 559.52,-12.8082 570.764,-24.8133 582.008,-37.0633 593.252,-49.5633 604.496,-62.3185 615.74,-75.3339 626.984,-88.6149 638.227,-102.167 649.471,-115.996 
 660.715,-130.106 671.959,-144.505 683.203,-159.198 694.447,-174.19 705.691,-189.489 716.934,-205.1 728.178,-221.029 739.422,-237.283 750.666,-253.869 761.91,-270.794 
 773.154,-288.063 784.397,-305.686 795.641,-323.668 806.885,-342.017 818.129,-360.74 829.373,-379.845 840.617,-399.341 851.861,-419.234 863.104,-439.533 874.348,-460.246 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -238.793,-460.246 -227.549,-439.533 -216.305,-419.234 -205.061,-399.341 -193.817,-379.845 -182.573,-360.74 -171.33,-342.017 -160.086,-323.668 -148.842,-305.686 -137.598,-288.063 
 -126.354,-270.794 -115.11,-253.869 -103.866,-237.283 -92.6226,-221.029 -81.3788,-205.1 -70.1349,-189.489 -58.8911,-174.19 -47.6473,-159.198 -36.4034,-144.505 -25.1596,-130.106 
 -13.9157,-115.996 -2.67186,-102.167 8.57198,-88.6149 19.8158,-75.3339 31.0597,-62.3185 42.3035,-49.5633 53.5474,-37.0633 64.7912,-24.8133 76.0351,-12.8082 87.2789,-1.04327 
 98.5228,10.4864 109.767,21.7855 121.01,32.8586 132.254,43.7102 143.498,54.3449 154.742,64.7668 165.986,74.9803 177.23,84.9895 188.474,94.7986 199.717,104.411 
 210.961,113.832 222.205,123.064 233.449,132.112 244.693,140.979 255.937,149.668 267.18,158.183 278.424,166.529 289.668,174.707 300.912,182.722 312.156,190.576 
 323.4,198.274 334.644,205.817 345.887,213.21 357.131,220.455 368.375,227.554 379.619,234.512 390.863,241.331 402.107,248.013 413.35,254.562 424.594,260.98 
 435.838,267.269 447.082,273.433 458.326,279.473 469.57,285.393 480.814,291.194 492.057,296.879 503.301,302.45 514.545,307.91 525.789,313.261 537.033,318.505 
 548.277,323.644 559.52,328.68 570.764,333.615 582.008,338.452 593.252,343.192 604.496,347.837 615.74,352.389 626.984,356.851 638.227,361.223 649.471,365.507 
 660.715,369.706 671.959,373.821 683.203,377.854 694.447,381.806 705.691,385.679 716.934,389.474 728.178,393.194 739.422,396.839 750.666,400.411 761.91,403.912 
 773.154,407.343 784.397,410.705 795.641,414 806.885,417.229 818.129,420.394 829.373,423.495 840.617,426.534 851.861,429.512 863.104,432.431 874.348,435.292 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [116]:
t = linspace(-2, 3, 200)
x = cos(t*pi*2) .* exp(t)
y = sin(t*pi*2) .* exp(t)
plot(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -10 
 
 
 0 
 
 
 10 
 
 
 20 
 
 
 -10 
 
 
 0 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 248.11,147.763 248.14,147.436 248.109,147.101 248.014,146.766 247.856,146.44 247.634,146.132 247.352,145.85 247.013,145.604 246.624,145.402 246.191,145.251 
 245.725,145.158 245.236,145.128 244.734,145.166 244.234,145.273 243.747,145.451 243.288,145.699 242.869,146.013 242.504,146.39 242.205,146.822 241.983,147.3 
 241.848,147.816 241.809,148.356 241.87,148.909 242.036,149.461 242.308,149.996 242.684,150.501 243.159,150.96 243.726,151.359 244.376,151.685 245.095,151.924 
 245.868,152.068 246.678,152.106 247.505,152.033 248.329,151.844 249.128,151.538 249.88,151.119 250.563,150.59 251.155,149.959 251.636,149.239 251.988,148.443 
 252.195,147.588 252.244,146.694 252.125,145.781 251.834,144.874 251.369,143.995 250.733,143.169 249.933,142.421 248.983,141.774 247.9,141.251 246.704,140.871 
 245.422,140.651 244.082,140.606 242.717,140.746 241.361,141.076 240.05,141.599 238.82,142.309 237.708,143.199 236.749,144.254 235.976,145.455 235.418,146.779 
 235.103,148.196 235.049,149.675 235.272,151.18 235.781,152.674 236.576,154.116 237.653,155.466 238.997,156.684 240.586,157.732 242.393,158.573 244.38,159.175 
 246.506,159.509 248.721,159.554 250.973,159.292 253.204,158.715 255.356,157.822 257.367,156.62 259.177,155.125 260.73,153.36 261.971,151.357 262.852,149.158 
 263.331,146.808 263.375,144.363 262.961,141.88 262.074,139.423 260.715,137.058 258.895,134.851 256.637,132.867 253.979,131.171 250.967,129.822 247.665,128.872 
 244.141,128.367 240.479,128.343 236.765,128.826 233.095,129.829 229.567,131.353 226.28,133.385 223.333,135.897 220.82,138.848 218.83,142.186 217.441,145.841 
 216.721,149.734 216.723,153.777 217.483,157.871 219.023,161.911 221.34,165.79 224.416,169.397 228.207,172.624 232.653,175.367 237.671,177.53 243.158,179.026 
 248.996,179.782 255.049,179.739 261.172,178.857 267.207,177.117 272.991,174.52 278.362,171.089 283.156,166.872 287.219,161.937 290.407,156.377 292.591,150.306 
 293.663,143.855 293.538,137.174 292.156,130.425 289.489,123.782 285.541,117.424 280.349,111.532 273.984,106.283 266.554,101.849 258.196,98.3865 249.082,96.0371 
 239.411,94.9194 229.407,95.1259 219.315,96.7197 209.395,99.7304 199.914,104.152 191.143,109.943 183.348,117.02 176.783,125.267 171.683,134.527 168.258,144.61 
 166.682,155.295 167.093,166.334 169.582,177.456 174.191,188.375 180.909,198.794 189.669,208.416 200.347,216.948 212.762,224.11 226.68,229.644 241.814,233.323 
 257.831,234.953 274.357,234.388 290.987,231.528 307.29,226.33 322.825,218.81 337.145,209.044 349.812,197.172 360.411,183.396 368.558,167.979 373.913,151.238 
 376.192,133.544 375.177,115.309 370.726,96.9841 362.777,79.0423 351.357,61.9729 336.588,46.2674 318.682,32.4067 297.946,20.8484 274.776,12.0134 249.653,6.27306 
 223.133,3.93701 195.838,5.24177 168.441,10.3409 141.655,19.2965 116.21,32.0731 92.8409,48.5337 72.2666,68.4375 55.1688,91.4414 42.1738,117.104 33.8327,144.89 
 30.6037,174.184 32.8345,204.297 40.7483,234.483 54.4309,263.956 73.8218,291.91 98.7081,317.535 128.722,340.041 163.344,358.679 201.904,372.761 243.598,381.685 
 287.498,384.952 332.568,382.184 377.69,373.143 421.687,357.743 463.351,336.057 501.471,308.33 534.868,274.975 562.426,236.574 583.123,193.872 596.063,147.763 
 
 "/>
 
 
 
 
 y1

In [117]:
plot(sin, 0, 2pi, label="sin")
plot!(cos, 0, 2pi, label="cos", c=:green)
plot!(x->1, 0, 2pi, c=:red, l=:dash, label="")
plot!(x->-1, 0, 2pi, c=:red, l=:dash, label="")
ylims!(-1.2, 1.2)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3328,35.6882 97.1342,35.6882 102.936,35.6882 108.737,

In [118]:
xticks!(0:pi/2:2pi)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0000000 
 
 
 1.5707963 
 
 
 3.1415927 
 
 
 4.7123890 
 
 
 6.2831853 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3

In [119]:
xticks!(0:pi/2:2pi, ["0", "\\pi /2", "\\pi", "3\\pi/2", "2\\pi"])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 π 
 
 
 /2 
 
 
 π 
 
 
 3 
 
 
 π 
 
 
 2 
 
 
 
 2 
 
 
 π 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3328,3

In [120]:
x = linspace(0, 2*pi, 100)
anim = Animation()
for i = 1:5:100
    plot(x[1:i], sin(x[1:i]))
    frame(anim)
end
gif(anim, "exemplo.gif", fps=10)

INFO: Saved animation to /home/abel/projetos/smne-2016-julia/exemplo.gif


Plots.AnimatedGif("/home/abel/projetos/smne-2016-julia/exemplo.gif")

In [121]:
x = linspace(0, 2*pi, 100)
anim = Animation()
for i = 1:3:100
    plot(x[1:i], sin(x[1:i]))
    xlims!(x[1], x[end])
    ylims!(-1, 1)
    frame(anim)
end
gif(anim, "exemplo2.gif", fps=12)

INFO: Saved animation to /home/abel/projetos/smne-2016-julia/exemplo2.gif


Plots.AnimatedGif("/home/abel/projetos/smne-2016-julia/exemplo2.gif")

In [122]:
x = linspace(0, 2*pi, 100)
anim = Animation()
for i = 1:3:100
    plot(x, sin(x), leg=false)
    a = x[i]
    scatter!([a], [sin(a)], c=:red)
    plot!(x, sin(a) + cos(a)*(x-a), c=:red, l=:dash)
    xlims!(x[1], x[end])
    ylims!(-2, 2)
    frame(anim)
end
gif(anim, "exemplo3.gif", fps=12)

INFO: Saved animation to /home/abel/projetos/smne-2016-julia/exemplo3.gif


Plots.AnimatedGif("/home/abel/projetos/smne-2016-julia/exemplo3.gif")

## Exercícios

Faça um gráfico